Fix failed spec in CI using jruby
```
An error occurred while installing rbs (3.5.1), and Bundler cannot continue.

In Gemfile:
  steep was resolved to 1.7.1, which depends on
    rbs
Error: The process '/home/runner/.rubies/jruby-9.4.7.0/bin/bundle' failed with exit code 5
```

See <https://github.com/GrottoPress/envy.rb/actions/runs/9555823265/job/26339829578>.